### ISSUE TITLE
Include another .sh scripts for usual programs

### ISSUE THREAD

**Issue by andreybleme** [andreybleme/my-ubash#1]
Include more scripts to easily install programs on debian based linux distributions.

**Comment by PokeAcer549** [comment]
What type of programs would you like? :P

**Comment by andreybleme** [comment]
@PokeAcer549 a lot of great programs such as Docker, python 2.x, 3.x, VLC and so on, were already added by great contributors. I'll close the isu now, so people can stop sending PRs with new scripts.
